//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type ActivityTime struct {
	ID        int32
	BeginTime string
	EndTime   string
}

const TypeId_ActivityTime = 1793126044

func (*ActivityTime) GetTypeId() int32 {
	return 1793126044
}

func (_v *ActivityTime) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		if _v.BeginTime, _ok_ = _buf["BeginTime"].(string); !_ok_ {
			err = errors.New("BeginTime error")
			return
		}
	}
	{
		var _ok_ bool
		if _v.EndTime, _ok_ = _buf["EndTime"].(string); !_ok_ {
			err = errors.New("EndTime error")
			return
		}
	}
	return
}

func DeserializeActivityTime(_buf map[string]interface{}) (*ActivityTime, error) {
	v := &ActivityTime{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
