//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type AttrAddition struct {
	Typ    int32
	ValTyp int32
	Val    int32
}

const TypeId_AttrAddition = 2072237689

func (*AttrAddition) GetTypeId() int32 {
	return 2072237689
}

func (_v *AttrAddition) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["typ"].(float64); !_ok_ {
			err = errors.New("typ error")
			return
		}
		_v.Typ = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["valTyp"].(float64); !_ok_ {
			err = errors.New("valTyp error")
			return
		}
		_v.ValTyp = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["val"].(float64); !_ok_ {
			err = errors.New("val error")
			return
		}
		_v.Val = int32(_tempNum_)
	}
	return
}

func DeserializeAttrAddition(_buf map[string]interface{}) (*AttrAddition, error) {
	v := &AttrAddition{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
