//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type BattleFallOut struct {
	ItemId     int32
	ItemAmount int32
	Weight     int32
}

const TypeId_BattleFallOut = 633121405

func (*BattleFallOut) GetTypeId() int32 {
	return 633121405
}

func (_v *BattleFallOut) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["itemId"].(float64); !_ok_ {
			err = errors.New("itemId error")
			return
		}
		_v.ItemId = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["itemAmount"].(float64); !_ok_ {
			err = errors.New("itemAmount error")
			return
		}
		_v.ItemAmount = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["weight"].(float64); !_ok_ {
			err = errors.New("weight error")
			return
		}
		_v.Weight = int32(_tempNum_)
	}
	return
}

func DeserializeBattleFallOut(_buf map[string]interface{}) (*BattleFallOut, error) {
	v := &BattleFallOut{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
