//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type BattleRule1 struct {
	ID    int32
	Tips1 string
	Tips2 string
	Tips3 string
	Tips4 string
}

const TypeId_BattleRule1 = 906584765

func (*BattleRule1) GetTypeId() int32 {
	return 906584765
}

func (_v *BattleRule1) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		if _v.Tips1, _ok_ = _buf["Tips1"].(string); !_ok_ {
			err = errors.New("Tips1 error")
			return
		}
	}
	{
		var _ok_ bool
		if _v.Tips2, _ok_ = _buf["Tips2"].(string); !_ok_ {
			err = errors.New("Tips2 error")
			return
		}
	}
	{
		var _ok_ bool
		if _v.Tips3, _ok_ = _buf["Tips3"].(string); !_ok_ {
			err = errors.New("Tips3 error")
			return
		}
	}
	{
		var _ok_ bool
		if _v.Tips4, _ok_ = _buf["Tips4"].(string); !_ok_ {
			err = errors.New("Tips4 error")
			return
		}
	}
	return
}

func DeserializeBattleRule1(_buf map[string]interface{}) (*BattleRule1, error) {
	v := &BattleRule1{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
