//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type BuffbuffCreate struct {
	Id   int32
	Buff int32
}

const TypeId_BuffbuffCreate = -1307410518

func (*BuffbuffCreate) GetTypeId() int32 {
	return -1307410518
}

func (_v *BuffbuffCreate) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ {
			err = errors.New("id error")
			return
		}
		_v.Id = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["buff"].(float64); !_ok_ {
			err = errors.New("buff error")
			return
		}
		_v.Buff = int32(_tempNum_)
	}
	return
}

func DeserializeBuffbuffCreate(_buf map[string]interface{}) (*BuffbuffCreate, error) {
	v := &BuffbuffCreate{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
