//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type BuffskillCD struct {
	Id int32
	Dt int32
}

const TypeId_BuffskillCD = -1853759529

func (*BuffskillCD) GetTypeId() int32 {
	return -1853759529
}

func (_v *BuffskillCD) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ {
			err = errors.New("id error")
			return
		}
		_v.Id = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["dt"].(float64); !_ok_ {
			err = errors.New("dt error")
			return
		}
		_v.Dt = int32(_tempNum_)
	}
	return
}

func DeserializeBuffskillCD(_buf map[string]interface{}) (*BuffskillCD, error) {
	v := &BuffskillCD{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
