//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type ChargeFirstReward struct {
	ID        int32
	ActID     int32
	Day       int32
	ItemBoxID int32
}

const TypeId_ChargeFirstReward = -2084825461

func (*ChargeFirstReward) GetTypeId() int32 {
	return -2084825461
}

func (_v *ChargeFirstReward) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ActID"].(float64); !_ok_ {
			err = errors.New("ActID error")
			return
		}
		_v.ActID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["Day"].(float64); !_ok_ {
			err = errors.New("Day error")
			return
		}
		_v.Day = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ItemBoxID"].(float64); !_ok_ {
			err = errors.New("ItemBoxID error")
			return
		}
		_v.ItemBoxID = int32(_tempNum_)
	}
	return
}

func DeserializeChargeFirstReward(_buf map[string]interface{}) (*ChargeFirstReward, error) {
	v := &ChargeFirstReward{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
