//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type Chat struct {
	ID          int32
	ChannelName string
	Color       string
	CDTime      int32
}

const TypeId_Chat = 2099064

func (*Chat) GetTypeId() int32 {
	return 2099064
}

func (_v *Chat) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		if _v.ChannelName, _ok_ = _buf["ChannelName"].(string); !_ok_ {
			err = errors.New("ChannelName error")
			return
		}
	}
	{
		var _ok_ bool
		if _v.Color, _ok_ = _buf["Color"].(string); !_ok_ {
			err = errors.New("Color error")
			return
		}
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["CD_time"].(float64); !_ok_ {
			err = errors.New("CD_time error")
			return
		}
		_v.CDTime = int32(_tempNum_)
	}
	return
}

func DeserializeChat(_buf map[string]interface{}) (*Chat, error) {
	v := &Chat{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
