//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type CumulativeLogin struct {
	ID        int32
	Day       int32
	DayName   string
	Icon      string
	ItemBoxID int32
}

const TypeId_CumulativeLogin = 239930902

func (*CumulativeLogin) GetTypeId() int32 {
	return 239930902
}

func (_v *CumulativeLogin) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["Day"].(float64); !_ok_ {
			err = errors.New("Day error")
			return
		}
		_v.Day = int32(_tempNum_)
	}
	{
		var _ok_ bool
		if _v.DayName, _ok_ = _buf["DayName"].(string); !_ok_ {
			err = errors.New("DayName error")
			return
		}
	}
	{
		var _ok_ bool
		if _v.Icon, _ok_ = _buf["Icon"].(string); !_ok_ {
			err = errors.New("Icon error")
			return
		}
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ItemBoxID"].(float64); !_ok_ {
			err = errors.New("ItemBoxID error")
			return
		}
		_v.ItemBoxID = int32(_tempNum_)
	}
	return
}

func DeserializeCumulativeLogin(_buf map[string]interface{}) (*CumulativeLogin, error) {
	v := &CumulativeLogin{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
