//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type DailyTask struct {
	ID        int32
	TaskLimit int32
	GroupID   int32
}

const TypeId_DailyTask = 805958430

func (*DailyTask) GetTypeId() int32 {
	return 805958430
}

func (_v *DailyTask) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["TaskLimit"].(float64); !_ok_ {
			err = errors.New("TaskLimit error")
			return
		}
		_v.TaskLimit = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["GroupID"].(float64); !_ok_ {
			err = errors.New("GroupID error")
			return
		}
		_v.GroupID = int32(_tempNum_)
	}
	return
}

func DeserializeDailyTask(_buf map[string]interface{}) (*DailyTask, error) {
	v := &DailyTask{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
