//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type DropLibrary struct {
	ID           int32
	Mark         string
	DropID       int32
	DropType     int32
	DropValue    int32
	DropRate     int32
	MinDropTimes int32
	MaxDropTimes int32
	BaseLineID   int32
	IsDitto      int32
}

const TypeId_DropLibrary = 2126797484

func (*DropLibrary) GetTypeId() int32 {
	return 2126797484
}

func (_v *DropLibrary) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		if _v.Mark, _ok_ = _buf["Mark"].(string); !_ok_ {
			err = errors.New("Mark error")
			return
		}
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["DropID"].(float64); !_ok_ {
			err = errors.New("DropID error")
			return
		}
		_v.DropID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["DropType"].(float64); !_ok_ {
			err = errors.New("DropType error")
			return
		}
		_v.DropType = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["DropValue"].(float64); !_ok_ {
			err = errors.New("DropValue error")
			return
		}
		_v.DropValue = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["DropRate"].(float64); !_ok_ {
			err = errors.New("DropRate error")
			return
		}
		_v.DropRate = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["MinDropTimes"].(float64); !_ok_ {
			err = errors.New("MinDropTimes error")
			return
		}
		_v.MinDropTimes = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["MaxDropTimes"].(float64); !_ok_ {
			err = errors.New("MaxDropTimes error")
			return
		}
		_v.MaxDropTimes = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["BaseLineID"].(float64); !_ok_ {
			err = errors.New("BaseLineID error")
			return
		}
		_v.BaseLineID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["IsDitto"].(float64); !_ok_ {
			err = errors.New("IsDitto error")
			return
		}
		_v.IsDitto = int32(_tempNum_)
	}
	return
}

func DeserializeDropLibrary(_buf map[string]interface{}) (*DropLibrary, error) {
	v := &DropLibrary{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
