//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type FallOut struct {
	ID       int32
	Rewards1 []*ItemReward
	Amount   int32
	Rewards2 []*BattleFallOut
}

const TypeId_FallOut = 580813235

func (*FallOut) GetTypeId() int32 {
	return 580813235
}

func (_v *FallOut) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _arr_ []interface{}
		var _ok_ bool
		if _arr_, _ok_ = _buf["Rewards1"].([]interface{}); !_ok_ {
			err = errors.New("Rewards1 error")
			return
		}

		_v.Rewards1 = make([]*ItemReward, 0, len(_arr_))

		for _, _e_ := range _arr_ {
			var _list_v_ *ItemReward
			{
				var _ok_ bool
				var _x_ map[string]interface{}
				if _x_, _ok_ = _e_.(map[string]interface{}); !_ok_ {
					err = errors.New("_list_v_ error")
					return
				}
				if _list_v_, err = DeserializeItemReward(_x_); err != nil {
					return
				}
			}
			_v.Rewards1 = append(_v.Rewards1, _list_v_)
		}
	}

	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["Amount"].(float64); !_ok_ {
			err = errors.New("Amount error")
			return
		}
		_v.Amount = int32(_tempNum_)
	}
	{
		var _arr_ []interface{}
		var _ok_ bool
		if _arr_, _ok_ = _buf["Rewards2"].([]interface{}); !_ok_ {
			err = errors.New("Rewards2 error")
			return
		}

		_v.Rewards2 = make([]*BattleFallOut, 0, len(_arr_))

		for _, _e_ := range _arr_ {
			var _list_v_ *BattleFallOut
			{
				var _ok_ bool
				var _x_ map[string]interface{}
				if _x_, _ok_ = _e_.(map[string]interface{}); !_ok_ {
					err = errors.New("_list_v_ error")
					return
				}
				if _list_v_, err = DeserializeBattleFallOut(_x_); err != nil {
					return
				}
			}
			_v.Rewards2 = append(_v.Rewards2, _list_v_)
		}
	}

	return
}

func DeserializeFallOut(_buf map[string]interface{}) (*FallOut, error) {
	v := &FallOut{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
