//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type GameNotice struct {
	ID          int32
	Notice      string
	NoticeType  int32
	NoticeNum   int32
	NoticeTimes int32
	NoticeLapse int32
}

const TypeId_GameNotice = -1821479542

func (*GameNotice) GetTypeId() int32 {
	return -1821479542
}

func (_v *GameNotice) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		if _v.Notice, _ok_ = _buf["Notice"].(string); !_ok_ {
			err = errors.New("Notice error")
			return
		}
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["NoticeType"].(float64); !_ok_ {
			err = errors.New("NoticeType error")
			return
		}
		_v.NoticeType = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["NoticeNum"].(float64); !_ok_ {
			err = errors.New("NoticeNum error")
			return
		}
		_v.NoticeNum = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["NoticeTimes"].(float64); !_ok_ {
			err = errors.New("NoticeTimes error")
			return
		}
		_v.NoticeTimes = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["NoticeLapse"].(float64); !_ok_ {
			err = errors.New("NoticeLapse error")
			return
		}
		_v.NoticeLapse = int32(_tempNum_)
	}
	return
}

func DeserializeGameNotice(_buf map[string]interface{}) (*GameNotice, error) {
	v := &GameNotice{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
