//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type ItemReward struct {
	Id  int32
	Num int32
}

const TypeId_ItemReward = -1878566262

func (*ItemReward) GetTypeId() int32 {
	return -1878566262
}

func (_v *ItemReward) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ {
			err = errors.New("id error")
			return
		}
		_v.Id = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["num"].(float64); !_ok_ {
			err = errors.New("num error")
			return
		}
		_v.Num = int32(_tempNum_)
	}
	return
}

func DeserializeItemReward(_buf map[string]interface{}) (*ItemReward, error) {
	v := &ItemReward{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
