//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type ItemHurtReward struct {
	Hurt int32
	Id   int32
	Num  int32
}

const TypeId_ItemHurtReward = -1725520391

func (*ItemHurtReward) GetTypeId() int32 {
	return -1725520391
}

func (_v *ItemHurtReward) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["hurt"].(float64); !_ok_ {
			err = errors.New("hurt error")
			return
		}
		_v.Hurt = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ {
			err = errors.New("id error")
			return
		}
		_v.Id = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["num"].(float64); !_ok_ {
			err = errors.New("num error")
			return
		}
		_v.Num = int32(_tempNum_)
	}
	return
}

func DeserializeItemHurtReward(_buf map[string]interface{}) (*ItemHurtReward, error) {
	v := &ItemHurtReward{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
