//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type MailTemp struct {
	ID       int32
	Title    string
	Content  string
	Sender   string
	Duration int32
}

const TypeId_MailTemp = 54357579

func (*MailTemp) GetTypeId() int32 {
	return 54357579
}

func (_v *MailTemp) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		if _v.Title, _ok_ = _buf["Title"].(string); !_ok_ {
			err = errors.New("Title error")
			return
		}
	}
	{
		var _ok_ bool
		if _v.Content, _ok_ = _buf["Content"].(string); !_ok_ {
			err = errors.New("Content error")
			return
		}
	}
	{
		var _ok_ bool
		if _v.Sender, _ok_ = _buf["Sender"].(string); !_ok_ {
			err = errors.New("Sender error")
			return
		}
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["Duration"].(float64); !_ok_ {
			err = errors.New("Duration error")
			return
		}
		_v.Duration = int32(_tempNum_)
	}
	return
}

func DeserializeMailTemp(_buf map[string]interface{}) (*MailTemp, error) {
	v := &MailTemp{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
