//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type NickName struct {
	ID     int32
	Prefix string
}

const TypeId_NickName = 134381742

func (*NickName) GetTypeId() int32 {
	return 134381742
}

func (_v *NickName) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		if _v.Prefix, _ok_ = _buf["Prefix"].(string); !_ok_ {
			err = errors.New("Prefix error")
			return
		}
	}
	return
}

func DeserializeNickName(_buf map[string]interface{}) (*NickName, error) {
	v := &NickName{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
