//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type NoviceNpc struct {
	ID         int32
	PlayTypeID int32
	NPCID      []int32
}

const TypeId_NoviceNpc = 1382720331

func (*NoviceNpc) GetTypeId() int32 {
	return 1382720331
}

func (_v *NoviceNpc) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["PlayTypeID"].(float64); !_ok_ {
			err = errors.New("PlayTypeID error")
			return
		}
		_v.PlayTypeID = int32(_tempNum_)
	}
	{
		var _arr_ []interface{}
		var _ok_ bool
		if _arr_, _ok_ = _buf["NPCID"].([]interface{}); !_ok_ {
			err = errors.New("NPCID error")
			return
		}

		_v.NPCID = make([]int32, 0, len(_arr_))

		for _, _e_ := range _arr_ {
			var _list_v_ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = _e_.(float64); !_ok_ {
					err = errors.New("_list_v_ error")
					return
				}
				_list_v_ = int32(_x_)
			}
			_v.NPCID = append(_v.NPCID, _list_v_)
		}
	}

	return
}

func DeserializeNoviceNpc(_buf map[string]interface{}) (*NoviceNpc, error) {
	v := &NoviceNpc{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
