//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type PetFeedValue struct {
	PartId   int32
	PlanetId int32
	Value    int32
}

const TypeId_PetFeedValue = -735242172

func (*PetFeedValue) GetTypeId() int32 {
	return -735242172
}

func (_v *PetFeedValue) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["partId"].(float64); !_ok_ {
			err = errors.New("partId error")
			return
		}
		_v.PartId = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["planetId"].(float64); !_ok_ {
			err = errors.New("planetId error")
			return
		}
		_v.PlanetId = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["value"].(float64); !_ok_ {
			err = errors.New("value error")
			return
		}
		_v.Value = int32(_tempNum_)
	}
	return
}

func DeserializePetFeedValue(_buf map[string]interface{}) (*PetFeedValue, error) {
	v := &PetFeedValue{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
