//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type PetAttribute struct {
	AttId  int32
	ValMin int32
	ValMax int32
	Weight int32
}

const TypeId_PetAttribute = 930493549

func (*PetAttribute) GetTypeId() int32 {
	return 930493549
}

func (_v *PetAttribute) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["attId"].(float64); !_ok_ {
			err = errors.New("attId error")
			return
		}
		_v.AttId = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["valMin"].(float64); !_ok_ {
			err = errors.New("valMin error")
			return
		}
		_v.ValMin = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["valMax"].(float64); !_ok_ {
			err = errors.New("valMax error")
			return
		}
		_v.ValMax = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["weight"].(float64); !_ok_ {
			err = errors.New("weight error")
			return
		}
		_v.Weight = int32(_tempNum_)
	}
	return
}

func DeserializePetAttribute(_buf map[string]interface{}) (*PetAttribute, error) {
	v := &PetAttribute{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
