//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type PetFashion struct {
	ID         int32
	FashionNum int32
}

const TypeId_PetFashion = 184233913

func (*PetFashion) GetTypeId() int32 {
	return 184233913
}

func (_v *PetFashion) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["FashionNum"].(float64); !_ok_ {
			err = errors.New("FashionNum error")
			return
		}
		_v.FashionNum = int32(_tempNum_)
	}
	return
}

func DeserializePetFashion(_buf map[string]interface{}) (*PetFashion, error) {
	v := &PetFashion{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
