//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type PetStone struct {
	ID        int32
	Type      int32
	Parameter []*SkillsReplaceSkill
	Recycle   int32
}

const TypeId_PetStone = 535664294

func (*PetStone) GetTypeId() int32 {
	return 535664294
}

func (_v *PetStone) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["Type"].(float64); !_ok_ {
			err = errors.New("Type error")
			return
		}
		_v.Type = int32(_tempNum_)
	}
	{
		var _arr_ []interface{}
		var _ok_ bool
		if _arr_, _ok_ = _buf["Parameter"].([]interface{}); !_ok_ {
			err = errors.New("Parameter error")
			return
		}

		_v.Parameter = make([]*SkillsReplaceSkill, 0, len(_arr_))

		for _, _e_ := range _arr_ {
			var _list_v_ *SkillsReplaceSkill
			{
				var _ok_ bool
				var _x_ map[string]interface{}
				if _x_, _ok_ = _e_.(map[string]interface{}); !_ok_ {
					err = errors.New("_list_v_ error")
					return
				}
				if _list_v_, err = DeserializeSkillsReplaceSkill(_x_); err != nil {
					return
				}
			}
			_v.Parameter = append(_v.Parameter, _list_v_)
		}
	}

	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["Recycle"].(float64); !_ok_ {
			err = errors.New("Recycle error")
			return
		}
		_v.Recycle = int32(_tempNum_)
	}
	return
}

func DeserializePetStone(_buf map[string]interface{}) (*PetStone, error) {
	v := &PetStone{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
