//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type PetTaskInfo struct {
	ID          int32
	Name        string
	Desp        string
	Quality     int32
	Duration    int32
	PetRequest  int32
	PartRequest int32
	Reward      []*ItemReward
	Weight      int32
}

const TypeId_PetTaskInfo = 47641074

func (*PetTaskInfo) GetTypeId() int32 {
	return 47641074
}

func (_v *PetTaskInfo) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		if _v.Name, _ok_ = _buf["Name"].(string); !_ok_ {
			err = errors.New("Name error")
			return
		}
	}
	{
		var _ok_ bool
		if _v.Desp, _ok_ = _buf["Desp"].(string); !_ok_ {
			err = errors.New("Desp error")
			return
		}
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["Quality"].(float64); !_ok_ {
			err = errors.New("Quality error")
			return
		}
		_v.Quality = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["Duration"].(float64); !_ok_ {
			err = errors.New("Duration error")
			return
		}
		_v.Duration = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["PetRequest"].(float64); !_ok_ {
			err = errors.New("PetRequest error")
			return
		}
		_v.PetRequest = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["PartRequest"].(float64); !_ok_ {
			err = errors.New("PartRequest error")
			return
		}
		_v.PartRequest = int32(_tempNum_)
	}
	{
		var _arr_ []interface{}
		var _ok_ bool
		if _arr_, _ok_ = _buf["Reward"].([]interface{}); !_ok_ {
			err = errors.New("Reward error")
			return
		}

		_v.Reward = make([]*ItemReward, 0, len(_arr_))

		for _, _e_ := range _arr_ {
			var _list_v_ *ItemReward
			{
				var _ok_ bool
				var _x_ map[string]interface{}
				if _x_, _ok_ = _e_.(map[string]interface{}); !_ok_ {
					err = errors.New("_list_v_ error")
					return
				}
				if _list_v_, err = DeserializeItemReward(_x_); err != nil {
					return
				}
			}
			_v.Reward = append(_v.Reward, _list_v_)
		}
	}

	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["Weight"].(float64); !_ok_ {
			err = errors.New("Weight error")
			return
		}
		_v.Weight = int32(_tempNum_)
	}
	return
}

func DeserializePetTaskInfo(_buf map[string]interface{}) (*PetTaskInfo, error) {
	v := &PetTaskInfo{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
