//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type Planet struct {
	ID         int32
	Name       string
	Describe   string
	Color      []int32
	PetVisible int32
}

const TypeId_Planet = -1901896264

func (*Planet) GetTypeId() int32 {
	return -1901896264
}

func (_v *Planet) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		if _v.Name, _ok_ = _buf["Name"].(string); !_ok_ {
			err = errors.New("Name error")
			return
		}
	}
	{
		var _ok_ bool
		if _v.Describe, _ok_ = _buf["Describe"].(string); !_ok_ {
			err = errors.New("Describe error")
			return
		}
	}
	{
		var _arr_ []interface{}
		var _ok_ bool
		if _arr_, _ok_ = _buf["Color"].([]interface{}); !_ok_ {
			err = errors.New("Color error")
			return
		}

		_v.Color = make([]int32, 0, len(_arr_))

		for _, _e_ := range _arr_ {
			var _list_v_ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = _e_.(float64); !_ok_ {
					err = errors.New("_list_v_ error")
					return
				}
				_list_v_ = int32(_x_)
			}
			_v.Color = append(_v.Color, _list_v_)
		}
	}

	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["PetVisible"].(float64); !_ok_ {
			err = errors.New("PetVisible error")
			return
		}
		_v.PetVisible = int32(_tempNum_)
	}
	return
}

func DeserializePlanet(_buf map[string]interface{}) (*Planet, error) {
	v := &Planet{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
