//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type Purchase struct {
	ID            int32
	Desc          string
	PurchaseID    string
	AppleAppStroe string
	GooglePlay    string
	Price         string
	Character     string
	RechargeType  int32
	ActID         int32
	ProductType   int32
}

const TypeId_Purchase = 1807968545

func (*Purchase) GetTypeId() int32 {
	return 1807968545
}

func (_v *Purchase) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ID"].(float64); !_ok_ {
			err = errors.New("ID error")
			return
		}
		_v.ID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		if _v.Desc, _ok_ = _buf["Desc"].(string); !_ok_ {
			err = errors.New("Desc error")
			return
		}
	}
	{
		var _ok_ bool
		if _v.PurchaseID, _ok_ = _buf["PurchaseID"].(string); !_ok_ {
			err = errors.New("PurchaseID error")
			return
		}
	}
	{
		var _ok_ bool
		if _v.AppleAppStroe, _ok_ = _buf["AppleAppStroe"].(string); !_ok_ {
			err = errors.New("AppleAppStroe error")
			return
		}
	}
	{
		var _ok_ bool
		if _v.GooglePlay, _ok_ = _buf["GooglePlay"].(string); !_ok_ {
			err = errors.New("GooglePlay error")
			return
		}
	}
	{
		var _ok_ bool
		if _v.Price, _ok_ = _buf["Price"].(string); !_ok_ {
			err = errors.New("Price error")
			return
		}
	}
	{
		var _ok_ bool
		if _v.Character, _ok_ = _buf["Character"].(string); !_ok_ {
			err = errors.New("Character error")
			return
		}
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["RechargeType"].(float64); !_ok_ {
			err = errors.New("RechargeType error")
			return
		}
		_v.RechargeType = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ActID"].(float64); !_ok_ {
			err = errors.New("ActID error")
			return
		}
		_v.ActID = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["ProductType"].(float64); !_ok_ {
			err = errors.New("ProductType error")
			return
		}
		_v.ProductType = int32(_tempNum_)
	}
	return
}

func DeserializePurchase(_buf map[string]interface{}) (*Purchase, error) {
	v := &Purchase{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
