//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type SkillsTriggerAction struct {
	Action    int32
	Condition []*SkillsTriggerCondition
}

const TypeId_SkillsTriggerAction = 2051794242

func (*SkillsTriggerAction) GetTypeId() int32 {
	return 2051794242
}

func (_v *SkillsTriggerAction) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["action"].(float64); !_ok_ {
			err = errors.New("action error")
			return
		}
		_v.Action = int32(_tempNum_)
	}
	{
		var _arr_ []interface{}
		var _ok_ bool
		if _arr_, _ok_ = _buf["condition"].([]interface{}); !_ok_ {
			err = errors.New("condition error")
			return
		}

		_v.Condition = make([]*SkillsTriggerCondition, 0, len(_arr_))

		for _, _e_ := range _arr_ {
			var _list_v_ *SkillsTriggerCondition
			{
				var _ok_ bool
				var _x_ map[string]interface{}
				if _x_, _ok_ = _e_.(map[string]interface{}); !_ok_ {
					err = errors.New("_list_v_ error")
					return
				}
				if _list_v_, err = DeserializeSkillsTriggerCondition(_x_); err != nil {
					return
				}
			}
			_v.Condition = append(_v.Condition, _list_v_)
		}
	}

	return
}

func DeserializeSkillsTriggerAction(_buf map[string]interface{}) (*SkillsTriggerAction, error) {
	v := &SkillsTriggerAction{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
