//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type SkillsReplaceSkill struct {
	SkillId        int32
	ReplaceSkillId int32
}

const TypeId_SkillsReplaceSkill = 722514505

func (*SkillsReplaceSkill) GetTypeId() int32 {
	return 722514505
}

func (_v *SkillsReplaceSkill) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["skillId"].(float64); !_ok_ {
			err = errors.New("skillId error")
			return
		}
		_v.SkillId = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["replaceSkillId"].(float64); !_ok_ {
			err = errors.New("replaceSkillId error")
			return
		}
		_v.ReplaceSkillId = int32(_tempNum_)
	}
	return
}

func DeserializeSkillsReplaceSkill(_buf map[string]interface{}) (*SkillsReplaceSkill, error) {
	v := &SkillsReplaceSkill{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
