//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type SkillsTriggerCondition struct {
	ConditionType  int32
	ConditionValue int32
}

const TypeId_SkillsTriggerCondition = -2031805809

func (*SkillsTriggerCondition) GetTypeId() int32 {
	return -2031805809
}

func (_v *SkillsTriggerCondition) Deserialize(_buf map[string]interface{}) (err error) {
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["conditionType"].(float64); !_ok_ {
			err = errors.New("conditionType error")
			return
		}
		_v.ConditionType = int32(_tempNum_)
	}
	{
		var _ok_ bool
		var _tempNum_ float64
		if _tempNum_, _ok_ = _buf["conditionValue"].(float64); !_ok_ {
			err = errors.New("conditionValue error")
			return
		}
		_v.ConditionValue = int32(_tempNum_)
	}
	return
}

func DeserializeSkillsTriggerCondition(_buf map[string]interface{}) (*SkillsTriggerCondition, error) {
	v := &SkillsTriggerCondition{}
	if err := v.Deserialize(_buf); err == nil {
		return v, nil
	} else {
		return nil, err
	}
}
