//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type JsonLoader func(string) ([]map[string]interface{}, error)

type Tables struct {
	TblCharacter         *TblCharacter
	TblSkillActive       *TblSkillActive
	TblSkillEffect       *TblSkillEffect
	TblSkillBuff         *TblSkillBuff
	TblMap               *TblMap
	TblMapItem           *TblMapItem
	TblBattleRule1       *TblBattleRule1
	TblBattleRule2       *TblBattleRule2
	TblBattleRule3       *TblBattleRule3
	TblBattleRule4       *TblBattleRule4
	TblGlobalConfig      *TblGlobalConfig
	TblMVP               *TblMVP
	TblChat              *TblChat
	TblPlaySelect        *TblPlaySelect
	TblCharacterLvup     *TblCharacterLvup
	TblItem              *TblItem
	TblNickName          *TblNickName
	TblMonster           *TblMonster
	TblCharacterUnlock   *TblCharacterUnlock
	TblChatEmoji         *TblChatEmoji
	TblSceneMonster      *TblSceneMonster
	TblStuff             *TblStuff
	TblRobotName         *TblRobotName
	TblTaskMain          *TblTaskMain
	TblPetEgg            *TblPetEgg
	TblPetPart           *TblPetPart
	TblPlanet            *TblPlanet
	TblPetSlot           *TblPetSlot
	TblPurchase          *TblPurchase
	TblShop              *TblShop
	TblItemBox           *TblItemBox
	TblChargeFirstReward *TblChargeFirstReward
	TblDayPointConfig    *TblDayPointConfig
	TblDayTarget         *TblDayTarget
	TblMonthCard         *TblMonthCard
	TblTermGift          *TblTermGift
	TblMedalReward       *TblMedalReward
	TblFeature           *TblFeature
	TblAiMatchFile       *TblAiMatchFile
	TblMailTemp          *TblMailTemp
	TblPetFashion        *TblPetFashion
	TblRankConfig        *TblRankConfig
	TblActivityTime      *TblActivityTime
	TblCumulativeLogin   *TblCumulativeLogin
	TblPetTask           *TblPetTask
	TblPetTaskInfo       *TblPetTaskInfo
	TblCharacterSkin     *TblCharacterSkin
	TblDropLibrary       *TblDropLibrary
	TblDropGroup         *TblDropGroup
	TblDailyTask         *TblDailyTask
	TblPetRefine         *TblPetRefine
	TblPickStone         *TblPickStone
	TblPetStone          *TblPetStone
	TblNoviceNpc         *TblNoviceNpc
	TblPetShape          *TblPetShape
	TblPveSettings       *TblPveSettings
	TblGameNotice        *TblGameNotice
}

func NewTables(loader JsonLoader) (*Tables, error) {
	var err error
	var buf []map[string]interface{}

	tables := &Tables{}
	if buf, err = loader("tblcharacter"); err != nil {
		return nil, err
	}
	if tables.TblCharacter, err = NewTblCharacter(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblskillactive"); err != nil {
		return nil, err
	}
	if tables.TblSkillActive, err = NewTblSkillActive(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblskilleffect"); err != nil {
		return nil, err
	}
	if tables.TblSkillEffect, err = NewTblSkillEffect(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblskillbuff"); err != nil {
		return nil, err
	}
	if tables.TblSkillBuff, err = NewTblSkillBuff(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblmap"); err != nil {
		return nil, err
	}
	if tables.TblMap, err = NewTblMap(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblmapitem"); err != nil {
		return nil, err
	}
	if tables.TblMapItem, err = NewTblMapItem(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblbattlerule1"); err != nil {
		return nil, err
	}
	if tables.TblBattleRule1, err = NewTblBattleRule1(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblbattlerule2"); err != nil {
		return nil, err
	}
	if tables.TblBattleRule2, err = NewTblBattleRule2(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblbattlerule3"); err != nil {
		return nil, err
	}
	if tables.TblBattleRule3, err = NewTblBattleRule3(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblbattlerule4"); err != nil {
		return nil, err
	}
	if tables.TblBattleRule4, err = NewTblBattleRule4(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblglobalconfig"); err != nil {
		return nil, err
	}
	if tables.TblGlobalConfig, err = NewTblGlobalConfig(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblmvp"); err != nil {
		return nil, err
	}
	if tables.TblMVP, err = NewTblMVP(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblchat"); err != nil {
		return nil, err
	}
	if tables.TblChat, err = NewTblChat(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblplayselect"); err != nil {
		return nil, err
	}
	if tables.TblPlaySelect, err = NewTblPlaySelect(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblcharacterlvup"); err != nil {
		return nil, err
	}
	if tables.TblCharacterLvup, err = NewTblCharacterLvup(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblitem"); err != nil {
		return nil, err
	}
	if tables.TblItem, err = NewTblItem(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblnickname"); err != nil {
		return nil, err
	}
	if tables.TblNickName, err = NewTblNickName(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblmonster"); err != nil {
		return nil, err
	}
	if tables.TblMonster, err = NewTblMonster(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblcharacterunlock"); err != nil {
		return nil, err
	}
	if tables.TblCharacterUnlock, err = NewTblCharacterUnlock(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblchatemoji"); err != nil {
		return nil, err
	}
	if tables.TblChatEmoji, err = NewTblChatEmoji(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblscenemonster"); err != nil {
		return nil, err
	}
	if tables.TblSceneMonster, err = NewTblSceneMonster(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblstuff"); err != nil {
		return nil, err
	}
	if tables.TblStuff, err = NewTblStuff(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblrobotname"); err != nil {
		return nil, err
	}
	if tables.TblRobotName, err = NewTblRobotName(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tbltaskmain"); err != nil {
		return nil, err
	}
	if tables.TblTaskMain, err = NewTblTaskMain(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblpetegg"); err != nil {
		return nil, err
	}
	if tables.TblPetEgg, err = NewTblPetEgg(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblpetpart"); err != nil {
		return nil, err
	}
	if tables.TblPetPart, err = NewTblPetPart(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblplanet"); err != nil {
		return nil, err
	}
	if tables.TblPlanet, err = NewTblPlanet(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblpetslot"); err != nil {
		return nil, err
	}
	if tables.TblPetSlot, err = NewTblPetSlot(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblpurchase"); err != nil {
		return nil, err
	}
	if tables.TblPurchase, err = NewTblPurchase(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblshop"); err != nil {
		return nil, err
	}
	if tables.TblShop, err = NewTblShop(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblitembox"); err != nil {
		return nil, err
	}
	if tables.TblItemBox, err = NewTblItemBox(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblchargefirstreward"); err != nil {
		return nil, err
	}
	if tables.TblChargeFirstReward, err = NewTblChargeFirstReward(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tbldaypointconfig"); err != nil {
		return nil, err
	}
	if tables.TblDayPointConfig, err = NewTblDayPointConfig(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tbldaytarget"); err != nil {
		return nil, err
	}
	if tables.TblDayTarget, err = NewTblDayTarget(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblmonthcard"); err != nil {
		return nil, err
	}
	if tables.TblMonthCard, err = NewTblMonthCard(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tbltermgift"); err != nil {
		return nil, err
	}
	if tables.TblTermGift, err = NewTblTermGift(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblmedalreward"); err != nil {
		return nil, err
	}
	if tables.TblMedalReward, err = NewTblMedalReward(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblfeature"); err != nil {
		return nil, err
	}
	if tables.TblFeature, err = NewTblFeature(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblaimatchfile"); err != nil {
		return nil, err
	}
	if tables.TblAiMatchFile, err = NewTblAiMatchFile(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblmailtemp"); err != nil {
		return nil, err
	}
	if tables.TblMailTemp, err = NewTblMailTemp(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblpetfashion"); err != nil {
		return nil, err
	}
	if tables.TblPetFashion, err = NewTblPetFashion(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblrankconfig"); err != nil {
		return nil, err
	}
	if tables.TblRankConfig, err = NewTblRankConfig(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblactivitytime"); err != nil {
		return nil, err
	}
	if tables.TblActivityTime, err = NewTblActivityTime(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblcumulativelogin"); err != nil {
		return nil, err
	}
	if tables.TblCumulativeLogin, err = NewTblCumulativeLogin(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblpettask"); err != nil {
		return nil, err
	}
	if tables.TblPetTask, err = NewTblPetTask(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblpettaskinfo"); err != nil {
		return nil, err
	}
	if tables.TblPetTaskInfo, err = NewTblPetTaskInfo(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblcharacterskin"); err != nil {
		return nil, err
	}
	if tables.TblCharacterSkin, err = NewTblCharacterSkin(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tbldroplibrary"); err != nil {
		return nil, err
	}
	if tables.TblDropLibrary, err = NewTblDropLibrary(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tbldropgroup"); err != nil {
		return nil, err
	}
	if tables.TblDropGroup, err = NewTblDropGroup(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tbldailytask"); err != nil {
		return nil, err
	}
	if tables.TblDailyTask, err = NewTblDailyTask(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblpetrefine"); err != nil {
		return nil, err
	}
	if tables.TblPetRefine, err = NewTblPetRefine(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblpickstone"); err != nil {
		return nil, err
	}
	if tables.TblPickStone, err = NewTblPickStone(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblpetstone"); err != nil {
		return nil, err
	}
	if tables.TblPetStone, err = NewTblPetStone(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblnovicenpc"); err != nil {
		return nil, err
	}
	if tables.TblNoviceNpc, err = NewTblNoviceNpc(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblpetshape"); err != nil {
		return nil, err
	}
	if tables.TblPetShape, err = NewTblPetShape(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblpvesettings"); err != nil {
		return nil, err
	}
	if tables.TblPveSettings, err = NewTblPveSettings(buf); err != nil {
		return nil, err
	}
	if buf, err = loader("tblgamenotice"); err != nil {
		return nil, err
	}
	if tables.TblGameNotice, err = NewTblGameNotice(buf); err != nil {
		return nil, err
	}
	return tables, nil
}
