//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblActivityTime struct {
	_dataMap  map[int32]*ActivityTime
	_dataList []*ActivityTime
}

func NewTblActivityTime(_buf []map[string]interface{}) (*TblActivityTime, error) {
	_dataList := make([]*ActivityTime, 0, len(_buf))
	dataMap := make(map[int32]*ActivityTime)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeActivityTime(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblActivityTime{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblActivityTime) GetDataMap() map[int32]*ActivityTime {
	return table._dataMap
}

func (table *TblActivityTime) GetDataList() []*ActivityTime {
	return table._dataList
}

func (table *TblActivityTime) Get(key int32) *ActivityTime {
	return table._dataMap[key]
}
