//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblAiMatchFile struct {
	_dataMap  map[int32]*AiMatchFile
	_dataList []*AiMatchFile
}

func NewTblAiMatchFile(_buf []map[string]interface{}) (*TblAiMatchFile, error) {
	_dataList := make([]*AiMatchFile, 0, len(_buf))
	dataMap := make(map[int32]*AiMatchFile)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeAiMatchFile(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblAiMatchFile{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblAiMatchFile) GetDataMap() map[int32]*AiMatchFile {
	return table._dataMap
}

func (table *TblAiMatchFile) GetDataList() []*AiMatchFile {
	return table._dataList
}

func (table *TblAiMatchFile) Get(key int32) *AiMatchFile {
	return table._dataMap[key]
}
