//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblBattleRule2 struct {
	_dataMap  map[int32]*BattleRule2
	_dataList []*BattleRule2
}

func NewTblBattleRule2(_buf []map[string]interface{}) (*TblBattleRule2, error) {
	_dataList := make([]*BattleRule2, 0, len(_buf))
	dataMap := make(map[int32]*BattleRule2)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeBattleRule2(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblBattleRule2{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblBattleRule2) GetDataMap() map[int32]*BattleRule2 {
	return table._dataMap
}

func (table *TblBattleRule2) GetDataList() []*BattleRule2 {
	return table._dataList
}

func (table *TblBattleRule2) Get(key int32) *BattleRule2 {
	return table._dataMap[key]
}
