//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblBattleRule1 struct {
	_dataMap  map[int32]*BattleRule1
	_dataList []*BattleRule1
}

func NewTblBattleRule1(_buf []map[string]interface{}) (*TblBattleRule1, error) {
	_dataList := make([]*BattleRule1, 0, len(_buf))
	dataMap := make(map[int32]*BattleRule1)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeBattleRule1(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblBattleRule1{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblBattleRule1) GetDataMap() map[int32]*BattleRule1 {
	return table._dataMap
}

func (table *TblBattleRule1) GetDataList() []*BattleRule1 {
	return table._dataList
}

func (table *TblBattleRule1) Get(key int32) *BattleRule1 {
	return table._dataMap[key]
}
