//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblCharacterSkin struct {
	_dataMap  map[int32]*CharacterSkin
	_dataList []*CharacterSkin
}

func NewTblCharacterSkin(_buf []map[string]interface{}) (*TblCharacterSkin, error) {
	_dataList := make([]*CharacterSkin, 0, len(_buf))
	dataMap := make(map[int32]*CharacterSkin)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeCharacterSkin(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblCharacterSkin{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblCharacterSkin) GetDataMap() map[int32]*CharacterSkin {
	return table._dataMap
}

func (table *TblCharacterSkin) GetDataList() []*CharacterSkin {
	return table._dataList
}

func (table *TblCharacterSkin) Get(key int32) *CharacterSkin {
	return table._dataMap[key]
}
