//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblCharacterLvup struct {
	_dataMap  map[int32]*CharacterLvup
	_dataList []*CharacterLvup
}

func NewTblCharacterLvup(_buf []map[string]interface{}) (*TblCharacterLvup, error) {
	_dataList := make([]*CharacterLvup, 0, len(_buf))
	dataMap := make(map[int32]*CharacterLvup)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeCharacterLvup(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblCharacterLvup{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblCharacterLvup) GetDataMap() map[int32]*CharacterLvup {
	return table._dataMap
}

func (table *TblCharacterLvup) GetDataList() []*CharacterLvup {
	return table._dataList
}

func (table *TblCharacterLvup) Get(key int32) *CharacterLvup {
	return table._dataMap[key]
}
