//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblChat struct {
	_dataMap  map[int32]*Chat
	_dataList []*Chat
}

func NewTblChat(_buf []map[string]interface{}) (*TblChat, error) {
	_dataList := make([]*Chat, 0, len(_buf))
	dataMap := make(map[int32]*Chat)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeChat(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblChat{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblChat) GetDataMap() map[int32]*Chat {
	return table._dataMap
}

func (table *TblChat) GetDataList() []*Chat {
	return table._dataList
}

func (table *TblChat) Get(key int32) *Chat {
	return table._dataMap[key]
}
