//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblChargeFirstReward struct {
	_dataMap  map[int32]*ChargeFirstReward
	_dataList []*ChargeFirstReward
}

func NewTblChargeFirstReward(_buf []map[string]interface{}) (*TblChargeFirstReward, error) {
	_dataList := make([]*ChargeFirstReward, 0, len(_buf))
	dataMap := make(map[int32]*ChargeFirstReward)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeChargeFirstReward(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblChargeFirstReward{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblChargeFirstReward) GetDataMap() map[int32]*ChargeFirstReward {
	return table._dataMap
}

func (table *TblChargeFirstReward) GetDataList() []*ChargeFirstReward {
	return table._dataList
}

func (table *TblChargeFirstReward) Get(key int32) *ChargeFirstReward {
	return table._dataMap[key]
}
