//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblChatEmoji struct {
	_dataMap  map[int32]*ChatEmoji
	_dataList []*ChatEmoji
}

func NewTblChatEmoji(_buf []map[string]interface{}) (*TblChatEmoji, error) {
	_dataList := make([]*ChatEmoji, 0, len(_buf))
	dataMap := make(map[int32]*ChatEmoji)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeChatEmoji(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblChatEmoji{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblChatEmoji) GetDataMap() map[int32]*ChatEmoji {
	return table._dataMap
}

func (table *TblChatEmoji) GetDataList() []*ChatEmoji {
	return table._dataList
}

func (table *TblChatEmoji) Get(key int32) *ChatEmoji {
	return table._dataMap[key]
}
