//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblDayTarget struct {
	_dataMap  map[int32]*DayTarget
	_dataList []*DayTarget
}

func NewTblDayTarget(_buf []map[string]interface{}) (*TblDayTarget, error) {
	_dataList := make([]*DayTarget, 0, len(_buf))
	dataMap := make(map[int32]*DayTarget)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeDayTarget(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblDayTarget{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblDayTarget) GetDataMap() map[int32]*DayTarget {
	return table._dataMap
}

func (table *TblDayTarget) GetDataList() []*DayTarget {
	return table._dataList
}

func (table *TblDayTarget) Get(key int32) *DayTarget {
	return table._dataMap[key]
}
