//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblDropGroup struct {
	_dataMap  map[int32]*DropGroup
	_dataList []*DropGroup
}

func NewTblDropGroup(_buf []map[string]interface{}) (*TblDropGroup, error) {
	_dataList := make([]*DropGroup, 0, len(_buf))
	dataMap := make(map[int32]*DropGroup)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeDropGroup(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblDropGroup{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblDropGroup) GetDataMap() map[int32]*DropGroup {
	return table._dataMap
}

func (table *TblDropGroup) GetDataList() []*DropGroup {
	return table._dataList
}

func (table *TblDropGroup) Get(key int32) *DropGroup {
	return table._dataMap[key]
}
