//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblDayPointConfig struct {
	_dataMap  map[int32]*DayPointConfig
	_dataList []*DayPointConfig
}

func NewTblDayPointConfig(_buf []map[string]interface{}) (*TblDayPointConfig, error) {
	_dataList := make([]*DayPointConfig, 0, len(_buf))
	dataMap := make(map[int32]*DayPointConfig)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeDayPointConfig(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblDayPointConfig{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblDayPointConfig) GetDataMap() map[int32]*DayPointConfig {
	return table._dataMap
}

func (table *TblDayPointConfig) GetDataList() []*DayPointConfig {
	return table._dataList
}

func (table *TblDayPointConfig) Get(key int32) *DayPointConfig {
	return table._dataMap[key]
}
