//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblDropLibrary struct {
	_dataMap  map[int32]*DropLibrary
	_dataList []*DropLibrary
}

func NewTblDropLibrary(_buf []map[string]interface{}) (*TblDropLibrary, error) {
	_dataList := make([]*DropLibrary, 0, len(_buf))
	dataMap := make(map[int32]*DropLibrary)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeDropLibrary(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblDropLibrary{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblDropLibrary) GetDataMap() map[int32]*DropLibrary {
	return table._dataMap
}

func (table *TblDropLibrary) GetDataList() []*DropLibrary {
	return table._dataList
}

func (table *TblDropLibrary) Get(key int32) *DropLibrary {
	return table._dataMap[key]
}
