//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblFeature struct {
	_dataMap  map[int32]*Feature
	_dataList []*Feature
}

func NewTblFeature(_buf []map[string]interface{}) (*TblFeature, error) {
	_dataList := make([]*Feature, 0, len(_buf))
	dataMap := make(map[int32]*Feature)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeFeature(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblFeature{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblFeature) GetDataMap() map[int32]*Feature {
	return table._dataMap
}

func (table *TblFeature) GetDataList() []*Feature {
	return table._dataList
}

func (table *TblFeature) Get(key int32) *Feature {
	return table._dataMap[key]
}
