//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblFallOut struct {
	_dataMap  map[int32]*FallOut
	_dataList []*FallOut
}

func NewTblFallOut(_buf []map[string]interface{}) (*TblFallOut, error) {
	_dataList := make([]*FallOut, 0, len(_buf))
	dataMap := make(map[int32]*FallOut)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeFallOut(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblFallOut{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblFallOut) GetDataMap() map[int32]*FallOut {
	return table._dataMap
}

func (table *TblFallOut) GetDataList() []*FallOut {
	return table._dataList
}

func (table *TblFallOut) Get(key int32) *FallOut {
	return table._dataMap[key]
}
