//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblGameNotice struct {
	_dataMap  map[int32]*GameNotice
	_dataList []*GameNotice
}

func NewTblGameNotice(_buf []map[string]interface{}) (*TblGameNotice, error) {
	_dataList := make([]*GameNotice, 0, len(_buf))
	dataMap := make(map[int32]*GameNotice)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeGameNotice(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblGameNotice{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblGameNotice) GetDataMap() map[int32]*GameNotice {
	return table._dataMap
}

func (table *TblGameNotice) GetDataList() []*GameNotice {
	return table._dataList
}

func (table *TblGameNotice) Get(key int32) *GameNotice {
	return table._dataMap[key]
}
