//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblItemBox struct {
	_dataMap  map[int32]*ItemBox
	_dataList []*ItemBox
}

func NewTblItemBox(_buf []map[string]interface{}) (*TblItemBox, error) {
	_dataList := make([]*ItemBox, 0, len(_buf))
	dataMap := make(map[int32]*ItemBox)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeItemBox(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblItemBox{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblItemBox) GetDataMap() map[int32]*ItemBox {
	return table._dataMap
}

func (table *TblItemBox) GetDataList() []*ItemBox {
	return table._dataList
}

func (table *TblItemBox) Get(key int32) *ItemBox {
	return table._dataMap[key]
}
