//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblMVP struct {
	_dataMap  map[int32]*MVP
	_dataList []*MVP
}

func NewTblMVP(_buf []map[string]interface{}) (*TblMVP, error) {
	_dataList := make([]*MVP, 0, len(_buf))
	dataMap := make(map[int32]*MVP)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeMVP(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblMVP{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblMVP) GetDataMap() map[int32]*MVP {
	return table._dataMap
}

func (table *TblMVP) GetDataList() []*MVP {
	return table._dataList
}

func (table *TblMVP) Get(key int32) *MVP {
	return table._dataMap[key]
}
