//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblMailTemp struct {
	_dataMap  map[int32]*MailTemp
	_dataList []*MailTemp
}

func NewTblMailTemp(_buf []map[string]interface{}) (*TblMailTemp, error) {
	_dataList := make([]*MailTemp, 0, len(_buf))
	dataMap := make(map[int32]*MailTemp)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeMailTemp(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblMailTemp{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblMailTemp) GetDataMap() map[int32]*MailTemp {
	return table._dataMap
}

func (table *TblMailTemp) GetDataList() []*MailTemp {
	return table._dataList
}

func (table *TblMailTemp) Get(key int32) *MailTemp {
	return table._dataMap[key]
}
