//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblMap struct {
	_dataMap  map[int32]*Map
	_dataList []*Map
}

func NewTblMap(_buf []map[string]interface{}) (*TblMap, error) {
	_dataList := make([]*Map, 0, len(_buf))
	dataMap := make(map[int32]*Map)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeMap(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblMap{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblMap) GetDataMap() map[int32]*Map {
	return table._dataMap
}

func (table *TblMap) GetDataList() []*Map {
	return table._dataList
}

func (table *TblMap) Get(key int32) *Map {
	return table._dataMap[key]
}
