//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblMonthCard struct {
	_dataMap  map[int32]*MonthCard
	_dataList []*MonthCard
}

func NewTblMonthCard(_buf []map[string]interface{}) (*TblMonthCard, error) {
	_dataList := make([]*MonthCard, 0, len(_buf))
	dataMap := make(map[int32]*MonthCard)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeMonthCard(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblMonthCard{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblMonthCard) GetDataMap() map[int32]*MonthCard {
	return table._dataMap
}

func (table *TblMonthCard) GetDataList() []*MonthCard {
	return table._dataList
}

func (table *TblMonthCard) Get(key int32) *MonthCard {
	return table._dataMap[key]
}
