//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblNickName struct {
	_dataMap  map[int32]*NickName
	_dataList []*NickName
}

func NewTblNickName(_buf []map[string]interface{}) (*TblNickName, error) {
	_dataList := make([]*NickName, 0, len(_buf))
	dataMap := make(map[int32]*NickName)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeNickName(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblNickName{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblNickName) GetDataMap() map[int32]*NickName {
	return table._dataMap
}

func (table *TblNickName) GetDataList() []*NickName {
	return table._dataList
}

func (table *TblNickName) Get(key int32) *NickName {
	return table._dataMap[key]
}
