//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblPetTask struct {
	_dataMap  map[int32]*PetTask
	_dataList []*PetTask
}

func NewTblPetTask(_buf []map[string]interface{}) (*TblPetTask, error) {
	_dataList := make([]*PetTask, 0, len(_buf))
	dataMap := make(map[int32]*PetTask)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializePetTask(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblPetTask{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblPetTask) GetDataMap() map[int32]*PetTask {
	return table._dataMap
}

func (table *TblPetTask) GetDataList() []*PetTask {
	return table._dataList
}

func (table *TblPetTask) Get(key int32) *PetTask {
	return table._dataMap[key]
}
