//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblPetEgg struct {
	_dataMap  map[int32]*PetEgg
	_dataList []*PetEgg
}

func NewTblPetEgg(_buf []map[string]interface{}) (*TblPetEgg, error) {
	_dataList := make([]*PetEgg, 0, len(_buf))
	dataMap := make(map[int32]*PetEgg)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializePetEgg(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblPetEgg{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblPetEgg) GetDataMap() map[int32]*PetEgg {
	return table._dataMap
}

func (table *TblPetEgg) GetDataList() []*PetEgg {
	return table._dataList
}

func (table *TblPetEgg) Get(key int32) *PetEgg {
	return table._dataMap[key]
}
