//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblPickStone struct {
	_dataMap  map[int32]*PickStone
	_dataList []*PickStone
}

func NewTblPickStone(_buf []map[string]interface{}) (*TblPickStone, error) {
	_dataList := make([]*PickStone, 0, len(_buf))
	dataMap := make(map[int32]*PickStone)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializePickStone(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblPickStone{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblPickStone) GetDataMap() map[int32]*PickStone {
	return table._dataMap
}

func (table *TblPickStone) GetDataList() []*PickStone {
	return table._dataList
}

func (table *TblPickStone) Get(key int32) *PickStone {
	return table._dataMap[key]
}
