//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblPlanet struct {
	_dataMap  map[int32]*Planet
	_dataList []*Planet
}

func NewTblPlanet(_buf []map[string]interface{}) (*TblPlanet, error) {
	_dataList := make([]*Planet, 0, len(_buf))
	dataMap := make(map[int32]*Planet)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializePlanet(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblPlanet{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblPlanet) GetDataMap() map[int32]*Planet {
	return table._dataMap
}

func (table *TblPlanet) GetDataList() []*Planet {
	return table._dataList
}

func (table *TblPlanet) Get(key int32) *Planet {
	return table._dataMap[key]
}
