//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblPurchase struct {
	_dataMap  map[int32]*Purchase
	_dataList []*Purchase
}

func NewTblPurchase(_buf []map[string]interface{}) (*TblPurchase, error) {
	_dataList := make([]*Purchase, 0, len(_buf))
	dataMap := make(map[int32]*Purchase)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializePurchase(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblPurchase{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblPurchase) GetDataMap() map[int32]*Purchase {
	return table._dataMap
}

func (table *TblPurchase) GetDataList() []*Purchase {
	return table._dataList
}

func (table *TblPurchase) Get(key int32) *Purchase {
	return table._dataMap[key]
}
