//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblPetSlot struct {
	_dataMap  map[int32]*PetSlot
	_dataList []*PetSlot
}

func NewTblPetSlot(_buf []map[string]interface{}) (*TblPetSlot, error) {
	_dataList := make([]*PetSlot, 0, len(_buf))
	dataMap := make(map[int32]*PetSlot)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializePetSlot(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblPetSlot{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblPetSlot) GetDataMap() map[int32]*PetSlot {
	return table._dataMap
}

func (table *TblPetSlot) GetDataList() []*PetSlot {
	return table._dataList
}

func (table *TblPetSlot) Get(key int32) *PetSlot {
	return table._dataMap[key]
}
