//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblPlaySelect struct {
	_dataMap  map[int32]*PlaySelect
	_dataList []*PlaySelect
}

func NewTblPlaySelect(_buf []map[string]interface{}) (*TblPlaySelect, error) {
	_dataList := make([]*PlaySelect, 0, len(_buf))
	dataMap := make(map[int32]*PlaySelect)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializePlaySelect(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblPlaySelect{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblPlaySelect) GetDataMap() map[int32]*PlaySelect {
	return table._dataMap
}

func (table *TblPlaySelect) GetDataList() []*PlaySelect {
	return table._dataList
}

func (table *TblPlaySelect) Get(key int32) *PlaySelect {
	return table._dataMap[key]
}
