//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblPveSettings struct {
	_dataMap  map[int32]*PveSettings
	_dataList []*PveSettings
}

func NewTblPveSettings(_buf []map[string]interface{}) (*TblPveSettings, error) {
	_dataList := make([]*PveSettings, 0, len(_buf))
	dataMap := make(map[int32]*PveSettings)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializePveSettings(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblPveSettings{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblPveSettings) GetDataMap() map[int32]*PveSettings {
	return table._dataMap
}

func (table *TblPveSettings) GetDataList() []*PveSettings {
	return table._dataList
}

func (table *TblPveSettings) Get(key int32) *PveSettings {
	return table._dataMap[key]
}
