//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblPetShape struct {
	_dataMap  map[int32]*PetShape
	_dataList []*PetShape
}

func NewTblPetShape(_buf []map[string]interface{}) (*TblPetShape, error) {
	_dataList := make([]*PetShape, 0, len(_buf))
	dataMap := make(map[int32]*PetShape)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializePetShape(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblPetShape{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblPetShape) GetDataMap() map[int32]*PetShape {
	return table._dataMap
}

func (table *TblPetShape) GetDataList() []*PetShape {
	return table._dataList
}

func (table *TblPetShape) Get(key int32) *PetShape {
	return table._dataMap[key]
}
