//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblPetStone struct {
	_dataMap  map[int32]*PetStone
	_dataList []*PetStone
}

func NewTblPetStone(_buf []map[string]interface{}) (*TblPetStone, error) {
	_dataList := make([]*PetStone, 0, len(_buf))
	dataMap := make(map[int32]*PetStone)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializePetStone(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblPetStone{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblPetStone) GetDataMap() map[int32]*PetStone {
	return table._dataMap
}

func (table *TblPetStone) GetDataList() []*PetStone {
	return table._dataList
}

func (table *TblPetStone) Get(key int32) *PetStone {
	return table._dataMap[key]
}
