//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblPetFashion struct {
	_dataMap  map[int32]*PetFashion
	_dataList []*PetFashion
}

func NewTblPetFashion(_buf []map[string]interface{}) (*TblPetFashion, error) {
	_dataList := make([]*PetFashion, 0, len(_buf))
	dataMap := make(map[int32]*PetFashion)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializePetFashion(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblPetFashion{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblPetFashion) GetDataMap() map[int32]*PetFashion {
	return table._dataMap
}

func (table *TblPetFashion) GetDataList() []*PetFashion {
	return table._dataList
}

func (table *TblPetFashion) Get(key int32) *PetFashion {
	return table._dataMap[key]
}
