//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblPetTaskInfo struct {
	_dataMap  map[int32]*PetTaskInfo
	_dataList []*PetTaskInfo
}

func NewTblPetTaskInfo(_buf []map[string]interface{}) (*TblPetTaskInfo, error) {
	_dataList := make([]*PetTaskInfo, 0, len(_buf))
	dataMap := make(map[int32]*PetTaskInfo)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializePetTaskInfo(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblPetTaskInfo{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblPetTaskInfo) GetDataMap() map[int32]*PetTaskInfo {
	return table._dataMap
}

func (table *TblPetTaskInfo) GetDataList() []*PetTaskInfo {
	return table._dataList
}

func (table *TblPetTaskInfo) Get(key int32) *PetTaskInfo {
	return table._dataMap[key]
}
