//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblSkillBuff struct {
	_dataMap  map[int32]*SkillBuff
	_dataList []*SkillBuff
}

func NewTblSkillBuff(_buf []map[string]interface{}) (*TblSkillBuff, error) {
	_dataList := make([]*SkillBuff, 0, len(_buf))
	dataMap := make(map[int32]*SkillBuff)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeSkillBuff(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblSkillBuff{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblSkillBuff) GetDataMap() map[int32]*SkillBuff {
	return table._dataMap
}

func (table *TblSkillBuff) GetDataList() []*SkillBuff {
	return table._dataList
}

func (table *TblSkillBuff) Get(key int32) *SkillBuff {
	return table._dataMap[key]
}
