//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblSkillEffect struct {
	_dataMap  map[int32]*SkillEffect
	_dataList []*SkillEffect
}

func NewTblSkillEffect(_buf []map[string]interface{}) (*TblSkillEffect, error) {
	_dataList := make([]*SkillEffect, 0, len(_buf))
	dataMap := make(map[int32]*SkillEffect)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeSkillEffect(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblSkillEffect{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblSkillEffect) GetDataMap() map[int32]*SkillEffect {
	return table._dataMap
}

func (table *TblSkillEffect) GetDataList() []*SkillEffect {
	return table._dataList
}

func (table *TblSkillEffect) Get(key int32) *SkillEffect {
	return table._dataMap[key]
}
