//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblStuff struct {
	_dataMap  map[int32]*Stuff
	_dataList []*Stuff
}

func NewTblStuff(_buf []map[string]interface{}) (*TblStuff, error) {
	_dataList := make([]*Stuff, 0, len(_buf))
	dataMap := make(map[int32]*Stuff)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeStuff(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblStuff{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblStuff) GetDataMap() map[int32]*Stuff {
	return table._dataMap
}

func (table *TblStuff) GetDataList() []*Stuff {
	return table._dataList
}

func (table *TblStuff) Get(key int32) *Stuff {
	return table._dataMap[key]
}
