//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblSkillActive struct {
	_dataMap  map[int32]*SkillActive
	_dataList []*SkillActive
}

func NewTblSkillActive(_buf []map[string]interface{}) (*TblSkillActive, error) {
	_dataList := make([]*SkillActive, 0, len(_buf))
	dataMap := make(map[int32]*SkillActive)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeSkillActive(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblSkillActive{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblSkillActive) GetDataMap() map[int32]*SkillActive {
	return table._dataMap
}

func (table *TblSkillActive) GetDataList() []*SkillActive {
	return table._dataList
}

func (table *TblSkillActive) Get(key int32) *SkillActive {
	return table._dataMap[key]
}
