//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblShop struct {
	_dataMap  map[int32]*Shop
	_dataList []*Shop
}

func NewTblShop(_buf []map[string]interface{}) (*TblShop, error) {
	_dataList := make([]*Shop, 0, len(_buf))
	dataMap := make(map[int32]*Shop)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeShop(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblShop{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblShop) GetDataMap() map[int32]*Shop {
	return table._dataMap
}

func (table *TblShop) GetDataList() []*Shop {
	return table._dataList
}

func (table *TblShop) Get(key int32) *Shop {
	return table._dataMap[key]
}
