//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TblTermGift struct {
	_dataMap  map[int32]*TermGift
	_dataList []*TermGift
}

func NewTblTermGift(_buf []map[string]interface{}) (*TblTermGift, error) {
	_dataList := make([]*TermGift, 0, len(_buf))
	dataMap := make(map[int32]*TermGift)
	for _, _ele_ := range _buf {
		if _v, err2 := DeserializeTermGift(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.ID] = _v
		}
	}
	return &TblTermGift{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TblTermGift) GetDataMap() map[int32]*TermGift {
	return table._dataMap
}

func (table *TblTermGift) GetDataList() []*TermGift {
	return table._dataList
}

func (table *TblTermGift) Get(key int32) *TermGift {
	return table._dataMap[key]
}
