version: '3'
services:
  game:
    environment:
      - NATS_URL=nats://game-nats:4222
      - DATABASE_URL=mongodb://game-mongodb:27017
      - CACHE_URL=redis://game-redis:6379
    container_name: game
    image: ${REGISTRY}/${GAME_NAME}:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "8081:8081"
      - "8888:8888"
    restart: always
    networks:
      - game-network
## Auto update container to latest image
#  watchtower:
#    image: containrrr/watchtower
#    volumes:
#      - /root/.docker/config.json:/config.json
#      - /var/run/docker.sock:/var/run/docker.sock
#    command:
#      --interval 30
#      --cleanup
#      --label-enable
networks:
  game-network: