version: '3.7'
services:
  game-redis:
    container_name: game-redis
    image: redis:7.0.13
    ports:
      - "6379:6379"
    #    command:
    #      --requirepass ${REDIS_HOST_PASSWORD}
    restart: always
    networks:
      - rumble-network
  game-mongodb:
    container_name: game-mongodb
    image: mongo:5.0.20
    env_file:
      - .env
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - rumble-network
  game-nats:
    container_name: game-nats
    image: nats:2.9.22
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    restart: always
    hostname: nats-server
    networks:
      - rumble-network
volumes:
  mongo-data:
networks:
  rumble-network: